% Add my code folders.
addpath('../dataManagement',...
    '../analysisFunctions',...
    '../plottingFunctions')
% Some of Steve Marrons code, most particularly pcaSM for PCA.
addpath('./functionMfiles/codeSM/General',...
    '../codeSM/BatchAdjust',...
    '../codeSM/Smoothing')
% Some other peoples code I have used.
addpath('../otherPeoplesCode')        
